import "server-only";
import path from "node:path";
import { mkdir, writeFile, readFile, unlink } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { ALLOWED_MIME, UPLOAD_LIMIT_BYTES } from "./constants";

function uploadDir() {
  return path.resolve(process.cwd(), process.env.UPLOAD_DIR ?? "./storage/uploads");
}

/** Checks the real file signature instead of trusting the browser supplied MIME type. */
function sniff(buf: Buffer): string | null {
  if (buf.subarray(0, 4).toString("latin1") === "%PDF") return "application/pdf";
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "image/jpeg";
  if (buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "image/png";
  if (buf.subarray(0, 4).toString("latin1") === "RIFF" && buf.subarray(8, 12).toString("latin1") === "WEBP") {
    return "image/webp";
  }
  return null;
}

export class UploadError extends Error {}

export async function saveUpload(file: File) {
  if (file.size === 0) throw new UploadError("فایل خالی است");
  if (file.size > UPLOAD_LIMIT_BYTES) throw new UploadError("حجم هر فایل حداکثر ۵ مگابایت است");
  const buf = Buffer.from(await file.arrayBuffer());
  const mime = sniff(buf);
  if (!mime) throw new UploadError("فقط فایل‌های PDF، JPG، PNG و WEBP مجاز هستند");

  const storedName = `${randomUUID()}.${ALLOWED_MIME[mime]}`;
  await mkdir(uploadDir(), { recursive: true });
  await writeFile(path.join(uploadDir(), storedName), buf);
  return {
    storedName,
    mimeType: mime,
    size: file.size,
    originalName: file.name.slice(0, 180) || storedName,
  };
}

export async function readUpload(storedName: string) {
  // storedName is generated by us, but guard against path traversal anyway.
  return readFile(path.join(uploadDir(), path.basename(storedName)));
}

export async function deleteUpload(storedName: string) {
  try {
    await unlink(path.join(uploadDir(), path.basename(storedName)));
  } catch {
    /* already gone */
  }
}
