import "server-only";
import path from "node:path";
import { mkdir, writeFile, readFile, unlink } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { put, get, del, head } from "@vercel/blob";
import { ALLOWED_MIME, UPLOAD_LIMIT_BYTES } from "./constants";

function uploadDir() {
  if (process.env.VERCEL) throw new Error("Connect a private Vercel Blob store before uploading documents");
  return path.resolve(process.cwd(), process.env.UPLOAD_DIR ?? "./storage/uploads");
}

/** Checks the real file signature instead of trusting the browser supplied MIME type. */
function sniff(buf: Buffer): string | null {
  if (buf.subarray(0, 4).toString("latin1") === "%PDF") return "application/pdf";
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "image/jpeg";
  if (buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "image/png";
  if (buf.subarray(0, 4).toString("latin1") === "RIFF" && buf.subarray(8, 12).toString("latin1") === "WEBP") {
    return "image/webp";
  }
  return null;
}

export class UploadError extends Error {}

/** A connected Blob store authenticates with a read-write token or, on newer stores, OIDC + store id. */
export function blobConfigured() {
  return Boolean(process.env.BLOB_READ_WRITE_TOKEN || process.env.BLOB_STORE_ID);
}

export function isOwnedStagingPath(pathname: unknown, userId: string): pathname is string {
  return typeof pathname === "string" && pathname.startsWith(`staging/${userId}/`) &&
    /^[a-zA-Z0-9/-]+$/.test(pathname) && pathname.split("/").length === 3 &&
    pathname.split("/")[2].length > 0;
}

export async function saveUpload(file: File) {
  if (file.size === 0) throw new UploadError("فایل خالی است");
  if (file.size > UPLOAD_LIMIT_BYTES) throw new UploadError("حجم هر فایل حداکثر ۵ مگابایت است");
  const buf = Buffer.from(await file.arrayBuffer());
  const mime = sniff(buf);
  if (!mime) throw new UploadError("فقط فایل‌های PDF، JPG، PNG و WEBP مجاز هستند");

  const storedName = `${randomUUID()}.${ALLOWED_MIME[mime]}`;
  let location = storedName;
  if (blobConfigured()) {
    const blob = await put(`documents/${storedName}`, buf, {
      access: "private", contentType: mime, addRandomSuffix: false,
    });
    location = blob.pathname;
  } else {
    await mkdir(uploadDir(), { recursive: true });
    await writeFile(path.join(uploadDir(), storedName), buf);
  }
  return {
    storedName: location,
    mimeType: mime,
    size: file.size,
    originalName: file.name.slice(0, 180) || storedName,
  };
}

export async function readUpload(storedName: string) {
  if (storedName.startsWith("documents/")) {
    const result = await get(storedName, { access: "private", useCache: false });
    if (!result || result.statusCode !== 200) throw new Error("File missing");
    return result.stream;
  }
  // storedName is generated by us, but guard against path traversal anyway.
  const file = await readFile(path.join(uploadDir(), path.basename(storedName)));
  return new Response(new Uint8Array(file)).body!;
}

export async function deleteUpload(storedName: string) {
  if (storedName.startsWith("documents/")) {
    await del(storedName);
    return;
  }
  try {
    await unlink(path.join(uploadDir(), path.basename(storedName)));
  } catch {
    /* already gone */
  }
}

/** Only accept staged objects in this authenticated user's namespace, never arbitrary URLs. */
export async function resolveUpload(value: FormDataEntryValue, userId: string): Promise<File> {
  if (value instanceof File) return value;
  let ref: { pathname?: unknown; name?: unknown };
  try { ref = JSON.parse(value); } catch { throw new UploadError("مدرک ارسالی معتبر نیست"); }
  if (!ref || typeof ref.name !== "string" || !isOwnedStagingPath(ref.pathname, userId)) {
    throw new UploadError("مدرک ارسالی معتبر نیست");
  }
  const info = await head(ref.pathname);
  if (info.size < 1 || info.size > UPLOAD_LIMIT_BYTES) throw new UploadError("حجم فایل معتبر نیست");
  const result = await get(ref.pathname, { access: "private", useCache: false });
  if (!result || result.statusCode !== 200) throw new UploadError("فایل پیدا نشد؛ دوباره بارگذاری کنید");
  const bytes = await new Response(result.stream).arrayBuffer();
  // saveUpload validates actual bytes and writes a fresh immutable permanent object.
  return new File([bytes], ref.name.slice(0, 180), { type: info.contentType });
}
